name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - esp32c3
          - esp32c6
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          scenario: button.scenario.yaml
          diagram_file: diagram.${{ matrix.target }}.json
